kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: wildfly:latest
  SourceLocation: .
  SourceType: local
  Ports:
  - "8080"
  Application: app
  Project: myproject
  Name: wildfly-test
  Url:
  - Name: wildfly-test-8080
    Port: 8080
